name: Dopamine Build

on:
  push:
    branches: [ main ]
    tags-ignore: [ '*' ]

jobs:
  build:
    runs-on: macos-13  # 确保使用较新的 macOS 版本
    env:
      THEOS_PACKAGE_SCHEME: rootless  # 专门为无根越狱配置

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Theos
        uses: actions/cache@v3
        with:
          path: |
            ~/theos
            ${{ github.workspace }}/theos
          key: dopamine-${{ runner.os }}-theos-${{ hashFiles('Makefile') }}

      - name: Setup Theos for Dopamine
        uses: axs66/theos-action@main
        with:
          theos_version: v2.6  # 使用较新稳定版
          sdk_version: 16.2    # 匹配 iOS 16.5

      - name: Install dpkg for rootless
        run: |
          brew install dpkg
          echo 'export PATH="/opt/homebrew/opt/dpkg/bin:$PATH"' >> ~/.zshrc

      - name: Build Rootless Package
        run: |
          export THEOS_PACKAGE_INSTALLATION_PREFIX=/var/jb  # 多巴胺专用路径
          make clean
          make package FINALPACKAGE=1 \
            THEOS_PACKAGE_SCHEME=rootless \
            TARGET=iphone:clang:16.5:15.0  # 指定目标版本

      - name: Verify Deb Structure
        run: |
          dpkg -c packages/*.deb | grep "/var/jb/Library/Keyboard/Themes" ||
            (echo "路径验证失败" && exit 1)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dopamine-Keyboard-Theme
          path: packages/*.deb
